#!/usr/local/bin/node


console.log('Hello my dear Kot!')
console.log('Please have a very very good day!')
console.log('I live you very much and very proud of my smart working pickle!!!')
console.log('Piu piu piu!')